version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: db-api-booking-futsal
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - my-network


networks:
  my-network:
    driver: bridge